"""changing

Revision ID: a680d0cd4a56
Revises: 7bebea553171
Create Date: 2024-07-12 16:03:08.573318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a680d0cd4a56'
down_revision = '7bebea553171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flash_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('textColour', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('backgroundColour', sa.String(length=7), nullable=True))
        batch_op.drop_column('colour')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flash_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('colour', sa.VARCHAR(length=7), nullable=True))
        batch_op.drop_column('backgroundColour')
        batch_op.drop_column('textColour')

    # ### end Alembic commands ###
